# Basic Windows container Dockerfile with GUI support
FROM mcr.microsoft.com/windows:ltsc2019

# Set working directory
WORKDIR C:\\app

# Example: Set the default command to run when the container starts
CMD ["c:\\windows\\system32\\cmd.exe"]
    