name: Build and Push Docker Images

on:
  repository_dispatch:
    types:
      - build-push
  pull_request:
    branches:
      - main
      - rc
  workflow_dispatch:
    inputs:
      no_cache:
        description: 'Build without cache'
        type: boolean
        default: false

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Switch to Windows Docker Daemon
        if: runner.os == 'Windows'
        run: |
          echo "Switching to Windows Docker Daemon"
          $contextName = docker context ls | Select-String -Pattern "windows" | ForEach-Object { $_.ToString().Trim() -split '\s+' | Select-Object -First 1 }
          docker context use $contextName
          docker info

      - name: Build and Push Docker Images
        run: npm run build -- --pull ${{ inputs.no_cache && '--no-cache' || '' }}

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        if: github.event_name != 'pull_request'
        run: |
          docker push --all-tags docdetective/docdetective
